LGUG2Z/komorebi

- komorebi-core/src/config_generation.rs
Quick fix for the float-rule command generation.
> float-rule Syntax Error Fixed

- .github/workflows/windows.yaml
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
Before merging this:
1. Add a PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN` (or rename the secret name in the workflow).
2. Fork https://github.com/microsoft/winget-pkgs under @LGUG2Z. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Sign the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs) for winget-pkgs.
If you would like to read about this action further, the documentation is [here](https://bittu.eu.org/docs/wr-intro), and the …
> ci(windows): add winget releaser workflow

- .github/workflows/windows.yaml
Winget Releaser now uses versioned tags instead of `latest`, and now uses `github.ref_name` as a fallback value for `release-tag` by default.
As mentioned in https://github.com/LGUG2Z/komorebi/pull/220#issuecomment-1260247941, please install the [Pull](https://github.com/apps/pull) app on the winget-pkgs fork to ensure that it is always updated.
> ci(winget): update workflow

- komorebi/src/window.rs
this commits adds a max number of attempts (5) to the call of set_foreground_window inside Window:Focus
> feat(wm): add max number of attempts to set foreground

- komorebi-core/src/lib.rs
- komorebi/src/process_command.rs
- komorebi/src/window.rs
- komorebi/src/windows_api.rs
- komorebic.lib.ahk
- komorebic/src/main.rs
this pr adds the ability to close and minimize the current focused window via SocketMessages and komorebic commands
The commands are `Close` and `Minimize`, the same applies to the SocketMessages
resolve #189
> feat(wm): add close and minimize cmd

- komorebi.sample.ahk
The sample config only provided three of the four required arguments in the example call to ActiveWindowBorderColour. Uncommenting the line as it was would raise an error from AuthoHotKey.
> fix(config): call ActiveWindowBorderColour with all required arguments in sample config

- whkdrc.sample
The whkd process does not start with an s - unless something is wrong or buggy on my computer, it is just "whkd.exe" and so it should be that in this file as well.
> Fix default whkd configuration file

- komorebi-core/src/lib.rs
- komorebi/src/monitor.rs
- komorebi/src/process_command.rs
- komorebi/src/window_manager.rs
- komorebic/src/main.rs
Basically this commit adds a command that allows you to swap two monitors, well it actually swaps the workspaces between the monitors.
Sorry if the main logic is a bit weird, I'm basically new to rust, like I did a bit of rust last year on this project, then I got really busy and stopped doing any rust, so I'm still having a lot of trouble with the borrow checker
if you have any suggestions of how to make it better/cleaner please let me know
> feat(swap-workspaces-monitor): command to swap focused monitor workspaces with another monitor

- komorebi/src/main.rs
It seems that since this commit (https://github.com/LGUG2Z/komorebi/commit/f87d4d520be4f242c3733186953b8a2558f132df), komorebi no longer supports the launch `AutoHotkey64.exe`.
I send you PR. Would you check this?
> fix(wm): refer AHK_EXE

- komorebic/src/main.rs
fix: If the provided configuration path unfortunately includes a space (like C:/Users/FirstName LastName/...), then komorebi fails to find the configuration file as it gets `'--config=C:/Users/FirstName LastName/...'` from komorebic which looks like only `C:/User/FirstName`. Wrapping the path in quotes helps komorebi to find the configuration file.
P.S. I'm new to contributing, so if this is improper formatting, or if there's a smart way to supply the config path already without needing this change, I'm open to learning. Thanks!
> fix: Allowed support for spaces in config path

- komorebi-core/src/arrangement.rs
- komorebi-core/src/default_layout.rs
- komorebi/src/workspace.rs
Currently only BSP layout and primary container of custom layouts can be resized. BSP layout is not very good for ultrawide screens and resizing only primary container is limiting. This PR adds resizing for `ultrawide-vertical-stack` layout and refactors some code related to resize calculation.
1. `Workspace::enforce_resize_constraints` can now enforce different constraints for different layouts and for those layouts that can not be resized `resize_dimensions` is explicitly set to 0 (previously everything was constrained as for BSP)
2. New function for constraining resizing of  `ultrawide-vertical-stack` layout, which can be resized differently then BSP
3. Layout calculation for `ultrawide-vertical-stack` now apply `resize_dimensions` via new function `calculate_ultrawide_adjustment`. …
> feat(wm): ultrawide layout resizing

- .github/workflows/windows.yaml
Winget Releaser now supports non-Windows runners, and `ubuntu-latest` is generally faster.
> ci(winget): change Winget Releaser job to `ubuntu-latest`

- komorebi-core/src/default_layout.rs
- komorebi-core/src/lib.rs
- komorebi/src/process_command.rs
- komorebi/src/window_manager.rs
- komorebic.lib.ahk
- komorebic/src/main.rs
Resolves issue: https://github.com/LGUG2Z/komorebi/issues/555#issuecomment-1751916248.
This PR:
- Adds command to support `Cycle(CycleDirection)` using `cycle_next` and `cycle_previous` on DefaultLayout
- As per discussion, this PR will only support cycling layouts for DefaultLayout and not for CustomLayout. https://github.com/LGUG2Z/komorebi/pull/556#discussion_r1349709174 <- Discussion link
> feat(cli): add cycle-layout command

- Cargo.lock
- Cargo.toml
- komorebi-core/Cargo.toml
- komorebi-core/src/custom_layout.rs
- komorebi-core/src/lib.rs
- komorebi/Cargo.toml
- komorebi/src/main.rs
- komorebi/src/monitor.rs
- komorebi/src/process_command.rs
- komorebi/src/process_movement.rs
- komorebi/src/static_config.rs
- komorebi/src/window.rs
- komorebi/src/window_manager.rs
- komorebi/src/windows_api.rs
- komorebi/src/winevent_listener.rs
- komorebi/src/workspace.rs
- komorebic/Cargo.toml
- komorebic/src/main.rs
I was just wandering around the codebase to get a bit familiar with it and it turned to a session of small refactors around paths handling.
This PR:
- Avoids unnecessary string allocation when tracing paths
- Replaces `mut path & path.push()` with `path.join()` which is nicer and more concise and the cost is the same since it was already allocating when cloning
- Avoids unncessary cloning of paths where applicable
- Use `dunce` crate to remove `UNC` prefix
- Improve performance of resolving `~` by avoiding unnecessary string allocations
- Resolve `~`, `$Env:USERPROFILE` and `$HOME` consistenly between different code paths
- Use `PathBuf` instead of `String` for paths in CLI args
I may have missed a couple of places but I think I covered 90% of path handling in the codebase
> refactor: cleanup path handling

- komorebic/src/main.rs
Fixes ahk launch with static config if user has spaces in arguments for ahk (ahk exe path or komorebi home directory)
Small test:
> fix(component): fix ahk invocation by adding quotes around arguments

- komorebi/src/process_command.rs
- komorebic/src/main.rs
Replace the client socket with replies sent on the other side of the querying stream, for both UDS and TCP clients. This has two results: unix socket clients such as komorebic no longer race on the socket bind, fixing the out of order bind error, and the response mixup conditions that could occur. Queries over TCP now receive replies over TCP, rather than replies being sent to a future or in-flight command line client.
> fix(cli,tcp): replies are sent on the requesting channel

- komorebi/src/hidden.rs
- komorebi/src/main.rs
- komorebi/src/process_event.rs
- komorebi/src/static_config.rs
- komorebi/src/window_manager.rs
- komorebi/src/windows_callbacks.rs
- komorebi/src/winevent_listener.rs
- Use a single thread to bind the hook, and then start dispatching.
- Use a blocking loop for message dispatching.
- Remove the locks around crossbeam channel, as it's already Send + Sync
> fix(komorebi): cleanup window event messaging

- komorebi-core/src/arrangement.rs
- komorebi-core/src/rect.rs
- komorebi/src/border.rs
- komorebi/src/lib.rs
- komorebi/src/monitor.rs
- komorebi/src/process_command.rs
- komorebi/src/process_event.rs
- komorebi/src/static_config.rs
- komorebi/src/window.rs
- komorebi/src/window_manager.rs
- komorebi/src/windows_api.rs
- komorebi/src/windows_callbacks.rs
- komorebi/src/workspace.rs
- schema.json
This includes three changes that could be included independently though each has some side effect that is adjusted by the latter to better align with the overall goal.
I set out to remove the inconsistent gap and miscoloration around windows. This was originating in the interactions with DWM decorations.
First the API that we're using to read window size is shifted to one that returns Window dimensions without including the DWM/theme decorations.
Next in order to fix a number of new regressions vs. the application database, we needed to remove the use of the invisible borders - these were a side effect of the DWM decorations. They're no longer needed, as application Window dimensions are now correct, with one notable interaction with theming (below).
Finally we move away from …
> Simpler and more precise border production

- komorebi/src/windows_api.rs
This fixes a regression from 344e6ad2fded71a1d4271ac1005cfea2837d2a86 that assumed we were declared DPI aware.
> fix(komorebi): don't scale for DPI, as we're not DPI aware

- komorebi/src/window_manager.rs
The default stacking behaviour for all layouts was to subtract 1 to the calculated index for movements to the right or down, basically, for any movement where the new index is greater than the current one. This was not working correctly for the Grid layout.
This PR adds a special case that prevents the adjustment to the target container index so it behaves correctly.
> fix(wm): adds special case for grid stacks to the right

- docs/example-configurations.md
- Add the default location for the `whkdrc` file so it is explicit for new users
- Add missing word in the `whkdrc` section
> docs(example configs):  add default location for the whkdrc file

- komorebi/src/process_event.rs
- komorebi/src/windows_callbacks.rs
Previously we were dropping events that don't pertain to managed windows, with one exception in should_manage that could probably do with further cleanup (DisplayChange). This first step fixes the latent border window problem, where we would retain a border window when the last managed window was closed and focus transitioned to an unmanaged window.
> komorebi: hide the border window when unmanged windows are focused

- komorebi/src/process_command.rs
- komorebi/src/window.rs
- komorebi/src/window_manager.rs
- komorebi/src/windows_api.rs
Use the same method as FancyZones to enable setting the foreground window. This makes it possible then to remove the thread attachment behaviors that have a number of other complex side effects, and aren't always allowed. In addition, cleanup old focus/raise methods some, in particular the border window is now explicitly not activated when it is raised, as it should never be activated.
I've also left some breadcrumbs in comments from investigation that I did while doing QA, that highlighted other issues.
> komorebi: use a new method to focus windows

- komorebi/src/process_event.rs
This gives us a stack trace style error report in the log when in debug mode, which makes it much quicker to track down the origin of an error.
> komorebi: report full errors in debug mode

- komorebi/src/process_event.rs
- komorebi/src/stackbar.rs
- komorebi/src/window.rs
As we have been working down some bugs from earlier changes, we introduced some additional error conditions in the logs. Now that the new focus approach is available, switching the stackbar to that means we can avoid needing to pass down ForceUpdate and FocusChange events for non-windows, which removes many of these cases.
In addition we do a check in should_manage that the target object is actually a window, ignoring the event if it is not.
> fix(wm): reduce errors from non-window events

- docs/komorebi.example.json
The example configuration mistakenly used the key `border_padding` in the place of `border_width`. As `border_padding` does not exist in the spec, modifying its value has no effect.
As this file is used by `komorebic quickstart`, new users will have this incorrect key in their default configuration. Notably, setting its value to `0` to remove gaps has no effect. The rest of the documentation uses the correct key, so users copying and pasting from that would not encounter the bug.
> fix(docs): correct typo in example config

- komorebi-core/src/arrangement.rs
- komorebi-core/src/default_layout.rs
- komorebi/src/workspace.rs
Added `resize` to all layouts except `grid` and works properly with `flip`.
I think the `right-main-vertical-stack layout` can be removed, since this can be achieved with `vertical-stack` + `horizontal filp`.
> feat(wm): add resize of all layouts except grid with filp

- komorebi/src/animation.rs
- komorebi/src/animation_manager.rs
- komorebi/src/lib.rs
- komorebi/src/window.rs
Added static animation state manager for tracking "in_progress" and "is_cancelled" states. The idea is not to have states in Animation struct but to keep them in HashMap<hwnd, AnimationState> behind reference (Arc<Mutex<>>). So we each animation frame we have access to state and can cancel animation if we have to.
Need review and testings
@raggi @LGUG2Z
> fix(animation): Fixed cancelling logic

- komorebi/src/animation.rs
- komorebi/src/window.rs
Only focused window was cancelling its animation because we call cancel in window::set_position and waiting for its cancelling. And because we waiting for cancelling second window is still moving. Second window will stop moving only after the first window. So I moved `cancel` call to Animation struct so its happening in its own thread and doesn't block others animation moves and cancels.
> fix(animation): Move cancel call to Animation struct

- docs/troubleshooting.md
- mkdocs.yml
- shell.nix
- adds `mkdocs` extensions:
- `admonition` (contextual information blocks)
- `pymdownx.highlight` (syntax highlighting)
- `pymdownx.superfences` (indented codeblocks)
- adds `troubleshooting.md`:
- addressing an issue where _komorebi_ no longer works following monitor suspension
Following a support request on Discord to figure out why _komorebi_ would no longer work from a display suspending, it turns out some monitors misbehave, causing _komorebi_ to no longer work as expected following wake.
The steps have been documented here to help others.
The _mkdocs_ extensions were added to convey this information clearly, as ordered numbering is broken unless code blocks are indented.
---
Run `mkdocs serve` in the repo root to view.
> docs(troubleshooting) addressing display suspension within monitor OSD

- komorebi-core/src/lib.rs
- komorebi/src/process_command.rs
- komorebic/src/main.rs
This pull request would add the ability for komorebi to always automatically promote the currently focused window.
> Auto promote focused window

- komorebi-core/src/animation.rs
- komorebi-core/src/lib.rs
- komorebi-core/src/rect.rs
- komorebi-gui/src/main.rs
- komorebi/src/animation.rs
- komorebi/src/animation_manager.rs
- komorebi/src/lib.rs
- komorebi/src/process_command.rs
- komorebi/src/process_event.rs
- komorebi/src/stackbar_manager/mod.rs
- komorebi/src/static_config.rs
- komorebi/src/window.rs
- komorebi/src/windows_api.rs
- komorebic/src/main.rs
This commit contains all the changes of #597 to make it easier to rebase with the latest changes on master post-v0.1.21.
> feat(animation): bring in changes from #597

- komorebi/src/core/default_layout.rs
Both cycle-previous and cycle-next were out of sync, This PR fixes this inconsistency.
> fix(cycle-layout): cycle-previous and cycle-next now match the same sequence

- .gitignore
- komorebi-bar/Cargo.toml
- komorebi-bar/src/network.rs
I added formatting to the network widget that prettifies bytes. 
I think it made sense to choose `KiB` as the minimum data unit, which could be changed by adding it to the settings, if needed.
I formatted the output on the activity readings with left padding to make it easier to read the values when they change constantly.
I changed the icons too, sorry 😄 
I think that the `to_pretty_bytes` function could be placed in a separate file so another widget can use it as well. For example if we want to display the size on the drives or ram.
I little bit of refactoring might be needed, I am pretty new to Rust :)
> feat(bar): to_pretty_bytes on network

- komorebi/src/process_command.rs
This commit fixes the cases where you'd call this command on a monitor which was not focused, for example by pressing a button on a bar like `komorebi-bar` or other when you had focus on another monitor. This change ensures that first we focus the monitor where the mouse cursor is, this way it will act on the monitor that you've just pressed instead of the monitor that was focused before.
> Fix(wm): update monitor focus before focus-stack-window

- komorebi-bar/src/cpu.rs
- komorebi-bar/src/main.rs
- komorebi-bar/src/memory.rs
- komorebi-bar/src/widget.rs
I thought I add the cpu widget.
One interesting issue I ran into is that the egui_phosphor::regular::CPU is giving me the wrong icon. I wonder if that is only me.
It should be [this one](https://phosphoricons.com/?q=%22cpu%22)
> Feature: cpu widget

- komorebi/src/process_event.rs
- komorebi/src/window_manager.rs
- komorebi/src/workspace.rs
This commit allows `workspace-rules` and `initial_workspace_rules` to be applied to floating windows. As a by product of this commit, now the command to show `visible-windows` will now also show the maximized windows, monocled windows and floating windows.
Should fix the issue #990
@LGUG2Z I know you wanted to handle the refactor of the `visible-windows` type of functions but since this one was needed for this PR I've already changed it...
There are two `TODO` comments I added on this commit that I would like to have your feedback on.
> feat(wm): apply workspace-rules to floating windows

- komorebi/src/windows_api.rs
This should fix a bug where the monitor index preferences might not be properly applied. This would affect users with 3 or more monitors the most.
Fixes #1056
(there might be other issues that are fixed by this, but I didn't have to time to go through all of them and check... might do that later...)
To explain the fix:
- Previously it was adding placeholders and then inserting the monitor at the correct index, which would shift the rest to the right, which depending on the order could end up with a wrong result
- Now we add placeholders until the current index (inclusive), then check if the current one at the index we want to put this monitor is a placeholder, if it is we replace it (remove -> insert).
@LGUG2Z I can't properly test this since I've only got two monitors. It is probably …
> fix(windows_api): correctly handle monitors preference indices

- docs/example-configurations.md
This wasn't specified anywhere that I could find which would lead to users not knowing why they couldn't resize their windows and think it was a bug. Like it has happened [here](https://discord.com/channels/898554690126630914/898554690608967786/1298175871697289268) on discord.
> docs(mkdocs): Add note about `Grid` layout not allowing resizing windows

- komorebi/src/process_event.rs
This commit makes sure we refocus the window on `Show` event when it is the only window on the workspace. This is needed because some windows some times send the `FocusChange` event before the `Show` event and on the first event we will be focusing the desktop window to unfocus any previous window from other workspace because the workspace will still be empty. So after adding the window we need to focus it again.
This fixes an issue brought up on discord by @amnweb [here](https://discord.com/channels/898554690126630914/898556726108901386/1294848652451516436)
> fix(wm): focus window on `Show` when there is only 1 window

- komorebi/src/workspace_reconciliator.rs
Sets last_focused_workspace on the workspace reconciliator when alt-tabbing.
Fixes #1086
> fix(wm): Set last focused workspace on alt-tab

- komorebi/src/border_manager/mod.rs
- komorebi/src/process_event.rs
- komorebi/src/static_config.rs
- komorebi/src/window_manager.rs
Don't know if you've noticed but I created a [PR](https://github.com/RamonUnch/AltSnap/pull/564) on AltSnap to allow compatibility with komorebi. I'm still waiting for that PR to be merged though. There is however a slight issue on that PR which is that when moving with altsnap the borders don't update in real time, only update when the move finishes.
This happens because currently, komorebi checks if a move is happening by checking if the left mouse is pressed and updates the borders when there is a move while the left mouse button is pressed (BTW this is why when moving with the keyboard using the system move it only updates after pressing enter). However, for some reason I AltSnap somehow steals this left button information and komorebi thinks the button is not pressed.
This PR makes …
> fix(borders): update borders location when moving with altsnap

- komorebi/src/process_event.rs
- komorebi/src/static_config.rs
- komorebi/src/window_manager.rs
This commit fixes the issue related to moving windows to/from a floating workspace to a tiled workspace. Previously the start of the move would be ignored however when moving back from a tiled workspace since it didn't know about the existance of that window it would also "move" that workspace focused tiled window without physically moving it, leaving it in a weird state that seemed like it was unmanaged. This commit changes the way this mouse moves are handled and now also handles moving `floating_windows` and even monocle or maximized windows.
Fixes #1065
> fix(wm): handle moving windows to/from floating workspaces

- komorebi/src/process_event.rs
Fixes the issue talked on discord [here](https://discord.com/channels/898554690126630914/898554690608967786/1301581412008202298) where when using `Hide` as hiding behaviour some windows were hidden and never restored, the same would happen if using stacks with apps that matched the tray_and_multi_window_identifiers
> fix(wm): stop making windows disappear when using `Hide` behaviour

- komorebi/src/process_command.rs
After investigating further the issue where commands would randomly stop working, we've noticed that the issue seems to be that somehow the listening thread gets stuck reading the unix socket, as in it continuously tries to read a socket on a connection that is not sending anything anymore. The result would be that komorebi would no longer be able to receive commands until it was restarted.
This fix adds a read timeout of 1s and it spawns a new thread to handle the stream reading and process of cmds. So in case this happens again, that specific processing thread will only be stuck for 1s but the rest of komorebi will never get stuck and should keep working normally.
@LGUG2Z I still don't know the cause of this issue, but this fix should work no matter what is causing it.
I did manage to …
> fix(wm): add read timeout to command socket

- komorebi/src/window_manager.rs
There was an issue where if you changed focus across monitors and the target monitor had a maximized window it would focus one of the containers beneath it instead. And if there were no containers it wouldn't focus anything, but instead keep focus on the previous monitor. This commit fixes that issue.
This was first brought up on discord [here](https://discord.com/channels/898554690126630914/1308841644853952543/1308841644853952543). The user has already tested this fix and it is working fine! Now is just a matter of deciding if we keep that code that centers the mouse on the screen, no matter what the value of "mff" is?
> fix(wm): focus maximized windows when moving focus across monitors

- komorebi/src/window.rs
Previously when moving floating windows across monitors we would keep the size of the window as it was. For most cases this would be ok. However for users with monitors with completely different sizes this could result on a window that would fill across monitors when moving from the bigger monitor to the smaller monitor.
This commit, attempts to resize the windows proportionally to the monitors' sizes.
There is currently a slight issue with some apps (so far I've only noticed it on 'Wezterm'...) where if the DPIs across monitors are different they don't seem to fully get the Windows OS DPI change completely applied,  but it seems that setting the `Wezterm` compatibility high DPI scaling override to "System" on the app's executable properties, fixes the issue. Since this is only 1 app (so …
> fix(wm): resize float windows moved across monitors

- komorebi/src/window.rs
When moving maximized floating windows across monitors they were magically disappearing! The window would be on the correct place, with the correct coordinates and size, its styles wouldn't change it would still have the `VISIBLE` style, however the window was invisible. If we used the system move to try to move it sometimes we would be able to see a bar on the top of the monitor and if we moved the window with the keyboard on the direction of another monitor then the window would start showing up on that monitor... So it was visible on that monitor but not on the one we just moved it into. After some investigation I decided to atribute that behavior to magic, since I couldn't find any other plausible explanation, if someone knows about this please tell me, I too would like to learn the …
> fix(wm): maximized floating windows move across monitors without disappearing

- komorebi/src/process_event.rs
- komorebi/src/window_manager.rs
- komorebi/src/window_manager_event.rs
Moves within a floating workspace were being considered as moves across monitors. This would cause a weird issue in a situation were you were trying to move a window to a monitor that had a floating workspace and already had a window there, which was matched on `floating_windows` rules so was a floating window. This floating window would be focused on top of the window we just moved with mouse once we let go of the mouse with a bunch of focus flickering between the two windows.
Since moves within a floating workspace were wrongfully being considered as across monitors the behavior above would always happen when we moved/resized a window on a floating workspace.
This PR changes how moves across monitors are defined so we don't wrongfully consider a move across monitor when it wasn't, it …
> Fix moving on floating workspaces

- komorebi/src/monitor.rs
- komorebi/src/process_command.rs
- komorebi/src/window_manager.rs
This commit fixes an issue where when trying to move floating windows or windows on a floating workspace across boundaries to another monitor using the `move_container_in_direction` it wouldn't move the floating windows physically, although it moved them internally on komorebi, resulting in weird and wrong behavior.
This commit creates a new method on `Monitor` to `add_container_with_direction` which takes a move direction and then uses the same logic that was previously on the `move_container_in_direction` function.
It changes the `move_container_to_monitor` function to take an optional move direction which if it is some will have this function call the new method `add_container_with_direction` instead of just `add_container`.
Lastly the `move_container_in_direction` function now when it …
> fix(wm): move floats in direction across monitors

- komorebi/src/border_manager/mod.rs
There is a bug where the border manager is checking if the foreground window is maximized to remove all the borders on that monitor. However this check for `is_maximized` didn't check if the foreground window in question was on the current monitor being iterated through. So when the foreground (focused) window was maximized, every borders on all monitors were being removed.
This fix makes sure we check if the foreground window is on the monitor being iterated through and only remove the borders on that specific monitor.
> fix(border): stop removing borders on wrong monitors

- komorebi/src/border_manager/border.rs
- komorebi/src/border_manager/mod.rs
This commit makes it so a floating window only has the floating border when it is focused, if not it has the `Unfocused` border. It also makes the 'focused_container' have the `Unfocused` border when it is not the foreground window, for example when we have a floating window focused instead.
This commit also changes the border's `window_kind` so that the stored borders actually have that value so we can check it later (This value wasn't being updated).
This commit also makes it so we properly invalidate the borders in the situations discussed above (for example when changing focus to/from a floating window we need the floating window border to update its ZOrder as well as the previously focused window).
Lastly this commit, changes the `WM_PAINT` code part of the border so that it now sets …
> fix(borders): properly handle borders ZOrder

- komorebi-bar/src/bar.rs
- komorebi-bar/src/battery.rs
- komorebi-bar/src/cpu.rs
- komorebi-bar/src/date.rs
- komorebi-bar/src/komorebi.rs
- komorebi-bar/src/media.rs
- komorebi-bar/src/memory.rs
- komorebi-bar/src/network.rs
- komorebi-bar/src/render.rs
- komorebi-bar/src/storage.rs
- komorebi-bar/src/time.rs
- komorebi-bar/src/widget.rs
This meant to contain a few smaller changes that I think would make the bar even better. I will try to keep this small.
- [fix(bar): only indicate focused window on stack](https://github.com/LGUG2Z/komorebi/commit/6e0b71ce3623ddc7b9f177d75970fe04e23b7944)
- [feat(bar): 5 new grouping styles for shadow and glow](https://github.com/LGUG2Z/komorebi/commit/c982cb069aa8b6e04bbc35dd6c74932304abb8b6)
- [feat(bar): indicate clickable widgets](https://github.com/LGUG2Z/komorebi/pull/1163/commits/9c47c700cc1c39b078df8a09d79520ea4cb62925)
- [feat(bar): network widget - added show_default_interface and use enab…](https://github.com/LGUG2Z/komorebi/pull/1163/commits/b89fd7b94d695260b87ed8d7bff19f88adef7686)
- [feat(bar): only collect enabled widgets](https://github.com/LGUG2Z/komorebi/pull/1163/commits …
> feat(bar): new grouping styles, hover effects on widgets and other small optimizations

- komorebi-bar/src/komorebi.rs
- komorebi-client/src/lib.rs
This PR adds a helper function `send_batch` to komorebi-client that allows sending multiple messages in a batch. 3rd party users of this library could already do this themselves but it is nice to have this helper to simplify it.
Then, on komorebi-bar it makes use of the new `send_batch` function to batch all the messages in one go when pressing the button to move between workspaces or when moving between stacked windows.
Since we are creating this messages in one go we won't be mistakenly changing the value of `mff` for the user.
It also only batches the `mff` messages when the `mff` value it's true, if it is already false there is no need to be sending those extra messages.
> Fix: prevent bar from changing `mff`

- komorebi-bar/src/bar.rs
- komorebi-bar/src/battery.rs
- komorebi-bar/src/cpu.rs
- komorebi-bar/src/date.rs
- komorebi-bar/src/komorebi.rs
- komorebi-bar/src/komorebi_layout.rs
- komorebi-bar/src/media.rs
- komorebi-bar/src/memory.rs
- komorebi-bar/src/network.rs
- komorebi-bar/src/render.rs
- komorebi-bar/src/selected_frame.rs
- komorebi-bar/src/storage.rs
- komorebi-bar/src/time.rs
This commit changes the way icons are displayed on the bar. There was an issue with how app icons were sized using `shrink_to_fit`. This has been changed to use `fit_to_exact_size` instead, relying on the font size as a starting point and scaling it to `1.4` of its size, making the icons to appear larger.
The same scaling was done to all the widget icons as well to make them look unified.
https://github.com/user-attachments/assets/bae030d4-d444-4f43-b7a9-e860d5a31583
Special thanks to @alex-ds13 for initiating this change. It would be most appreciated if this PR is merged before [his](https://github.com/LGUG2Z/komorebi/pull/1177)
> feat(bar): scaled icon size relying on the font size

- komorebi-bar/src/bar.rs
- komorebi-bar/src/komorebi.rs
- komorebi-bar/src/widget.rs
This commit makes the `workspaces` on `Komorebi` widget optional. This way it allows adding the `workspaces` on one Alignment and the `focused_window` on another one, for example.
~~For some reason if you had some widget on the `center_widgets` with only icons, like the `focused_window` with just icons or the `workspaces` with just icons and nothing else, EGUI wouldn't show the icon properly. I believe that on the first frame the icons might not have been loaded yet, so it set the height of the `center_widgets` Area to 0 and afterwards it wouldn't grow to fit the icons unless we've made some config change for example.~~
~~To fix this we've made the icons have fixed size which is equal to the font size. For this it was required that the font size was added to the `RenderConfig` so that the …
> feat(bar): optional workspaces on Komorebi widget

- komorebi/src/core/mod.rs
- komorebi/src/main.rs
- komorebi/src/process_command.rs
- komorebi/src/window_manager.rs
- komorebic/src/main.rs
This PR creates a new `SocketMessage` called `StopIgnoreRestore` which makes komorebi stop without calling `window.restore()` on all windows. This way every maximized window will stay maximized once you start komorebi again and it is able to use the previous `State`.
If it fails to restore the previous state you might have to call `komorebic restore-windows` in case you had hidden windows, for example when when using the `window_hiding_behaviour` as `Hide`, or you can simply unminimize them if you were using `Cloak` or `Minimize`.
This PR is built on top #1185 so it needs to be merged after that one.
@LGUG2Z I've made this just a draft PR so you can give me your feedback and tell me if you think it's fine to add or if you rather not add it to not increase complexity just to appease the …
> Feature(wm)/stop ignore restore

- komorebi-bar/src/bar.rs
- komorebi-bar/src/komorebi.rs
- komorebi-bar/src/render.rs
This commit changes the way each of the 3 parts of potential widgets (left, center and right) is created so that they are all done on the same way and look the same. It is using `Area` with different anchors for each part which makes the widgets actually center vertically properly.
This created an issue with the `Bar` grouping. To fix it we've made the `Bar` grouping change the outer panel frame instead of creating an actual group. This has the side effect (or maybe feature!) of losing the background of the outer frame. Meaning this outer frame will now have the look of the `Bar` grouping only. Currently it is using a fixed outer margin but this can be changed in the future to a config option.
> fix(bar): normalize areas of widgets

- komorebi-bar/src/network.rs
There was an issue with the network widget when the widget spacing was applied on an alignment.
The same `RenderConfig` must be used for an alignment in order to maintain widget spacing, as it is necessary to remember the first time the `apply_on_widget` is called.
A boolean is used for that, which was not passed on to other widgets from the network widget, this is now fixed.
> fix(bar): network widget spacing

- komorebi-bar/src/bar.rs
- komorebi-bar/src/komorebi.rs
Previously when changing between themes with different backgrounds the widget's background color was not updating because they take the bg color from the `RenderConfig` which was only being updated on `apply_config`, now we also pass the `RenderConfig` to the `apply_theme` function and update it's `background_color` there as well.
> fix(bar): update widgets background color properly

- komorebi-bar/src/bar.rs
- komorebi-bar/src/config.rs
- komorebi-bar/src/render.rs
This commit adds `icon_scale` setting to the config that allows to set the icon scaling relative to the font size. This custom value is limited between 1.0 and 2.0 and has a default value of 1.4.
> feat(bar): added icon_scale to the config

- komorebi-bar/src/main.rs
Sometimes the bar would randomly stop receiving notifications from komorebi and would stop updating the `Komorebi` widget. This feels to me that the reason is the same one that used to happen on the `process_commands` from `komorebi` where the socket would get stuck reading an empty connection. This commit adds a read timeout to the socket to prevent that from happening and hopefully it should stop those situations where the bar would stop receiving notifications.
There were some users reporting on Discord that the bar would sometime stop updating the workspaces widget and I have faced that as well! Hopefully this should fix that. I looked if there was an opened issue on github related to this but couldn't find any, so maybe it was just reported on Discord.
> fix(bar): prevent komorebi connection from staling

- docs/komorebi.bar.example.json
- komorebi-bar/src/bar.rs
- komorebi-bar/src/config.rs
- komorebi-bar/src/komorebi.rs
- komorebi-bar/src/main.rs
- komorebi-bar/src/render.rs
- schema.bar.json
Old users will still be able to use the old options, however it should be discouraged or even deprecated to use the following configs:
- `work_area_offset` inside `monitor`
- `position`
- `frame`
If you remove all the options above the bar will still show up with a default height of 50 and a default padding of 10 all around.
If you need to customize the bar height, padding or margin you should use these new options:
- `height`: the height you want for the bar itself
- `margin`: this option allows you to set a margin around the bar (`default: 0`). You can either set it like this:
```jsonc
"margin": 10 // It will use a spacing of 10 on all sides of the bar
```
or like this:
```jsonc
"margin": {
"vertical": 10 // It will use a spacing of 10 above and below the bar
}
```
or like this …
> Fix(bar): simplify bar config

- komorebi/src/workspace.rs
- komorebic/src/main.rs
This commit removes the code on the workspace `update` on `layout-rules` where it was setting the `layout-flip` to `None` if the layout was different from `BSP`. This appears to be some old code when the layout-flip would only apply to the `BSP` layout. However now it appears to apply to all layouts so this code shouldn't exist. This commit also changes the docs from the `FlipLayout` command to remove the statement that only applied to `BSP` since it is no longer true.
> fix(wm): stop wrongfully removing layout-flip

- komorebi-bar/src/komorebi.rs
- komorebi-client/src/lib.rs
- komorebi/src/core/mod.rs
- komorebi/src/core/pathext.rs
Environment variables were not supported in the location of the configuration switcher section as described in #1131.
I've decided to make an extension called `PathExt` (name debatable) that replaces _any_ environment variable in a PathBuf.
It supports the following:
```json
"configuration_switcher": {
"enable": true,
"configurations": {
"home": "$HOME/komorebi.json",
"work": "$Env:USERPROFILE/komorebi.work.json"
}
}
```
My proposal is to use this extension other places as well in order to support any env vars in paths. Could it perhaps be used [here](https://github.com/LGUG2Z/komorebi/blob/a575b28422b45ca4dc3cabef55009fed59fcf3be/komorebi/src/core/mod.rs#L496)?
> fix(bar): resolve env vars in the configuration switcher

- komorebi-bar/src/bar.rs
- komorebi-bar/src/komorebi.rs
- komorebi-client/src/lib.rs
- komorebi/src/lib.rs
- komorebi/src/monitor_reconciliator/hidden.rs
- komorebi/src/monitor_reconciliator/mod.rs
This PR allows notifying the subscribers of any monitor events like display connection change or work area change. It also makes use of these new monitor notifications on the komorebi-bar to update the bar when the displays connections changes.
> Notify monitor events to subscribers

- komorebi/src/lib.rs
[The Configuration Reference](https://komorebi.lgug2z.com/schema#window_hiding_behaviour) and [Rust Doc](https://github.com/LGUG2Z/komorebi/blob/2d2b6e5c1552b046b783517f4875647a88a3e00b/komorebi/src/static_config.rs#L346) both state that the default hiding behaviour is `Cloak`, however, the default was actually set to `Minimize`.
While this technically changes the behaviour for anyone who doesn't have this option explicitly set, I feel it's more important to match the documentation, especially considering the other options were soft deprecated almost a year ago in cc7dbde0497ac9186d1325e3514c4d037f5af6b5 and the obvious issues `Minimize` causes when switching workspaces.
I noticed this after removing the config option since I thought it was redundant, which caused the workspace switching …
> Fix the default hiding behaviour not matching the documentation

- komorebi/src/main.rs
System::new_all() pulls all information (processes, cpu, mem, etc) but we only need process information. In addition currently it is being polled twice. System::new() creates an uninitialized struct, then we poll specifically for process info.
> perf(komorebi): dont pull redundant info from sysinfo::System

- komorebi-bar/src/network.rs
I realized that the `|` is not really necessary, so it is now removed.
before:
after:
> fix(bar): removed unneeded separator character on network widget

- komorebi-bar/src/bar.rs
This commit adds Thai font fallback to Leelawadee UI. This will be looked up at runtime on the user's system, and only loaded if the files exist in the default Windows font installation location.
> feat(bar): add thai font fallback

- komorebi/src/window_manager.rs
- komorebi/src/workspace.rs
@LGUG2Z I've noticed lately that some of my workspace rules weren't being applied. After looking for the cause I found out this happened after I disconnected and reconnected monitors when testing. All because we set the serde skip here: https://github.com/LGUG2Z/komorebi/pull/1241#discussion_r1929649354
So on this PR I'm removing the serde skip (or setting it to skip only when it is `None`) and to prevent sending it on `State` to all the subscribers I've change the way the `State` is created "from" the `WindowManager` to strip some unneeded parts, in this case the `workspace_config` from all workspaces by setting it to `None`.
Although this method can be used in the future to strip down even more things from the monitors and/or workspaces in case we want to reduce the size of `State` that …
> fix(wm): monitor reconnect

- komorebi/src/main.rs
- komorebi/src/monitor_reconciliator/mod.rs
- komorebi/src/process_command.rs
- komorebi/src/process_event.rs
- komorebi/src/reaper.rs
- komorebi/src/static_config.rs
- komorebi/src/window_manager.rs
This PR changes the way the reaper works.
First it changed the `known_hwnds` held by the `WindowManager` to be a HashMap of window handles (isize) to a pair of monitor_idx, workspace_idx (usize, usize).
Then it changes the reaper to have a cache of hwnds which is updated by the `WindowManager` when they change. The reaper has a thread that is continuously checking this cache to see if there is any window handle that no longer exists. When it finds them, the thread sends a notification to a channel which is then received by the reaper on another thread that actually does the work on the `WindowManager` by removing said windows.
This means that the reaper no longer tries to access and lock the `WindowManager` every second like it used to, but instead it only does it when it actually needs, …
> feat(reaper): rework reaper logic to make it faster

- komorebi/src/workspace.rs
Previously if a workspace had any floating windows it would always focus the first one when restoring. Now it only focus the floating window if the workspace layer is `Floating`.
> fix(wm): take layer into account on ws restore

- komorebi/src/window_manager.rs
When toggling monocle mode it hides all the other containers but it wasn't hiding the floating windows. Now it hides and restores them as well.
> fix(wm): hide/restore floating windows on monocle toggle

- komorebi-client/src/lib.rs
- komorebi/src/monitor.rs
- komorebi/src/reaper.rs
- komorebi/src/static_config.rs
- komorebi/src/window_manager.rs
- komorebi/src/workspace.rs
- schema.json
This commit adds the ability to set a container and workspace padding per monitor. To do so and to simplify any future need of changing some value per monitor and have it pass through to each workspace a new field was added to the `Workspace` called `globals` which has a new struct called `WorkspaceGlobals` which includes any global values that might be needed by the workspace.
This field is updated by the monitor for all its workspaces whenever the config is loaded or reloaded. It is also updated on `RetileAll` and on the function `update_focused_workspace`. This should make sure that every time a workspace needs to use it's `update` function it has all the `globals` up to date!
This also means that now the `update` function from workspaces doesn't take any argument at all, reducing all …
> feat(wm): add padding per monitor

- komorebi-bar/src/bar.rs
- komorebi/src/monitor_reconciliator/mod.rs
This PR fixes an issue where if you started komorebi without one of the monitors and then reconnected the monitor later it wasn't properly loading the data from `win32-display-data`.
It also fixes a bug on the komorebi-bar by making sure the bar applies the `work_area_offset` correctly after a monitor reconnects. Since if it is the first time the monitor is connecting it won't have the offset cached yet.
Fixes #1294
> fix(wm): monitor reconnect after komorebi start

- komorebi/src/main.rs
- komorebi/src/reaper.rs
Previously the reaper at startup would lock it's own `HWNDS_CACHE` and then try to lock the WM to get its `known_hwnds`, however if there was an event in the mean time, the process_event would lock the WM first and then it would try to lock the reaper's `HWNDS_CACHE` to update it but it would deadlock since that would be locked by the reaper waiting for the WM to be released.
This PR now makes it so we pass the `known_hwnds` to the reaper as an argument at startup and it also rearranges the order of loading the listeners. Now it first loads all the manager type listeners and only after it does it load the commands and events listeners. After some testing this seems to be the best order that doesn't cause any issues at all! There were some other issues that I've noticed before when …
> Fix reaper deadlock

- komorebi-bar/src/config.rs
- komorebi-bar/src/komorebi.rs
- komorebi-bar/src/render.rs
- schema.bar.json
Fixes #1013
Added a new option to show all the icons on the komorebi workspace widget. 
In order to distinguish between focused and non-focused windows, the icon(s) of focused window(s) on a workspace are scaled, while the non-focused icons are text sized.
https://github.com/user-attachments/assets/e5647e93-db69-4d6a-8915-1a2e0cebe8d6
---
I am open to change the name of the setting or even consider always loading all the icons from the state, instead of checking the config in the render.rs.
My idea was to optimize for performance, so the icons would only be loaded for all the containers if needed. If it gives little to no advantage, the code would be cleaner when all the icons are loaded regardless of the setting.
Please let me know what you prefer
> feat(bar): added option to show all icons on the komorebi workspace

- komorebi-bar/src/komorebi.rs
- komorebi-bar/src/komorebi_layout.rs
This commit makes sure that the accent color is used on certain bar components, such as active workspace, selected layout and focused window.
This will now make these components stand out even more for a better visual indication.
Fixes #1288
https://github.com/user-attachments/assets/50135377-510f-4fd7-8a10-d544de493534
```json
"theme": {
"palette": "Base16",
"name": "AyuMirage",
"accent": "Base0D"
},
```
> fix(bar): use accent color for active widget components

- komorebi/src/border_manager/border.rs
- komorebi/src/border_manager/mod.rs
- komorebi/src/process_command.rs
- komorebi/src/window.rs
- komorebi/src/window_manager.rs
- komorebi/src/windows_api.rs
This PR includes 3 commits:
- The first commit changes the `komorebic toggle-workspace-layer` command to move up/down all windows of the layer. So if you are on the `Tiling` layer and toggle the layer it will bring all floating windows to front so you can see them and cycle through them. Once you toggle again, the floating windows are sent back again.
- The second commit fixes a memory leak on the border manager. More information is provided on the commit message itself
- The third commit fixes an issue with the stacking of windows, which was causing issues with the borders. The fix also makes possible to stack windows on all directions. Previously if you had focus on a stack and tried to call `stack-window` on a direction with index higher than the current focus (usually right or down), …
> Fix(borders): multiple borders fixes

- komorebi-bar/src/selected_frame.rs
This commit fixes a breaking change on the selected_frame that was introduced by eframe version 0.31.
In this version, the stroke is drawn on the inside of a Frame instead it being drawn on the outside like before. This now means that a stroke needs to be added on all the states of the Frame in order to avoid all the elements to be moving around on hover.
> fix(bar): always add stroke on selected_frame

- komorebi/src/container.rs
- komorebi/src/window_manager.rs
This is a simple fix to make it so every time we call `load_focused_window` on a container we ignore the borders, since this function will only be performing hiding/restoring of windows if that container is a stack and in that case we want the container border to not be hidden so it doesn't flicker.
> fix(borders): ignore borders on all stack updates

- Cargo.lock
- komorebi/Cargo.toml
- komorebi/src/main.rs
- komorebi/src/window_manager.rs
- komorebi/tests/window_manager.rs
Created a test that creates the WM instance and ensures the instance is running. The test creates a custom socket and then cleans up the socket file after completion. Created a test that creates a WM instance, monitor instance, and workpace. The tests checks to ensure that the expected workspace is focused properly.
> test(window_manger.rs): tests: WM Instance and Focus Workspace

- Cargo.lock
- Cargo.toml
- komorebi-bar/Cargo.toml
- komorebi-bar/src/date.rs
- komorebi-bar/src/time.rs
- schema.bar.json
This commit adds a new setting on the time and date widgets to set the timezone.
In case the timezone is invalid, the time is replaced with an error message.
Use a custom format to display additional information.
```json
{
"Time": {
"enable": true,
"format": { "Custom": "%T %Z (Tokyo)" },
"timezone": "Asia/Tokyo"
}
}
```
```json
{
"Date": {
"enable": true,
"format": { "Custom": "%H:%M %e %b %Z (Tokyo)" },
"timezone": "Asia/Tokyo"
}
}
```
Closes: #1312
> feat(bar): added timezone to time widget

- komorebi/src/window_manager.rs
Added tests to test switching monitor focus, setting workspace name, and monitor size. Created a helper function for setting up the window manager instance and test socket.
> test(window_manager.rs): workspace and monitor tests

- Cargo.lock
- komorebi-bar/Cargo.toml
- komorebi-bar/src/date.rs
- komorebi-bar/src/time.rs
- schema.bar.json
This commit adds a little Easter egg on the time widget.
Use the `changing_icon` setting to enable this feature.
Based on the current time, the widget will use different icons to indicate certain activities of the day.
00:00 MOON
06:00 ALARM
06:01 BREAD
06:30 BARBELL
08:00 COFFEE
08:30 CLOCK
12:00 HAMBURGER
12:30 CLOCK_AFTERNOON
18:00 FORK_KNIFE
18:30 MOON_STARS
> feat(bar): changing icons based on the time

- komorebi/src/process_command.rs
- komorebi/src/window_manager.rs
Previously if we had a stack on a monocle container and tried to cycle stack or move the window within the stack or even using the focus stack window from a bar it would focus the wrong window and temporarely show that wrong window. This commit fixes this.
> fix(wm): focus correct window if monocled stack

- komorebi/src/monitor.rs
- komorebi/src/window_manager.rs
There was an issue where if you tried to move a floating window to another monitor using a command like `komorebic cycle-move-to-monitor 1` it would move the window correctly, but the target workspace layer wouldn't change, which probably meant it would still be as `Tiling` so if you tried to move the floating window with the new floating window moves it would behave as if it was a tile move and actually moved the window across monitor again if that was the direction you moved, any other direction would just be ignored.
This PR fixes that.
> fix(wm): update layer on cross monitor moves

- komorebi/src/window_manager.rs
This commit fixes an issue where the move/resize functions for floating windows weren't properly taking into account the coordinates of secondary monitors and were only working correctly on the main monitor where top/left was 0/0.
This issue was first brought up by a user on [Discord](https://discord.com/channels/898554690126630914/1348547975055409152)
> fix(wm): correct float window move/resize

- komorebi/src/lib.rs
- komorebi/src/monitor_reconciliator/mod.rs
- komorebi/src/process_command.rs
- komorebi/src/static_config.rs
- komorebi/src/window_manager.rs
- komorebi/src/windows_api.rs
Use the preferred id set by the user as the key when caching monitors. This way if a user is having issues with the `device_id` on their system they can use the `serial_number_id` on `display_index_preferences`. If instead a user is having issues with the `serial_number_id` they can make sure to use the `device_id` on `display_index_preferences`. Komorebi will use the preferred one as a key when caching the monitors.
@LGUG2Z This PR also includes a change of the `DISPLAY_INDEX_PREFERENCES` from a `Mutex` to `RwLock`. I believe the `RwLock` is better since it allows multiple readers at the same time, while the mutex blocks on all calls even if you just want to read or compare some value. For display index preferences (same thing applies to other existing mutexes) most times we access it is …
> fix(wm): use preferred id when caching monitors

- komorebi-bar/src/komorebi.rs
- komorebi-bar/src/komorebi_layout.rs
This commit adds the `focus-monitor-at-cursor` command on all the toggle buttons as the monitor idx is not sent as a parameter and the monitor needs to be focused when these buttons are clicked on the bar (especially for multiple bars)
> fix(bar): added missing `focus-monitor-at-cursor` command to buttons

- komorebi/src/border_manager/mod.rs
This PR reverts the commit that introduced multiple render passes (5919f88b389d8f73ad6d799b1e05801bcfd4c2aa) for the borders since that is not needed to fix the issue it was trying to fix. This PR includes the actual fix for that issue.
> fix: better border across monitor fix

- komorebi/src/window_manager.rs
- komorebi/src/workspace.rs
As mentioned on Discord this PR reverts the previous commit that turned on the `float_override` when switching to the `Floating` layer and turned it off when switching to the `Tiling` layer since this would result in an overwrite of the user config.
This PR uses a different method to accomplish the same behaviour without overwriting the user's config. It changes the `window_management_behaviour()` function to check the behaviour for the workspace in question and then it checks if the workspace has the `float_override` set or if the workspace layer is `Floating`.
> fix: forced float-override on `Floating` layer without overwriting user config

- komorebi/src/window_manager.rs
- komorebi/src/workspace.rs
This commit removes some workarounds on the `update_focused_workspace` function that were there to fix issues related to some bugs on the `workspace.restore()` function. This commit fixes the bugs on the `restore` function instead. The `update_focused_workspace` function should be used only to update a workspace layout.
> fix(wm): fix bugs on workspace restore and remove workarounds

- komorebi/src/workspace.rs
Created tests for testing the different adding and removing container functions. Also created a test to test the contains_window function.
> test(workspace.rs): tests for testing adding and removing containers

- komorebi/src/process_event.rs
This commit changes the behaviour of when floating windows are centered by making them only center when we are on a `WorkspaceLayer::Floating` and the window doesn't match a `floating_windows` rule and the workspace is not a floating workspace.
> fix(wm): change when floating windows are centered

- komorebi-client/src/lib.rs
- komorebi/src/lib.rs
This commit reexports the `win32_display_data` crate so that any 3rd party app that needs it can get it through the `komorebi-client` without having to keep manually synchronizing it with the version used by komorebi.
> feat(client): reexport win32_display_data

- komorebi/src/monitor.rs
- komorebi/src/process_command.rs
- komorebi/src/process_event.rs
- komorebi/src/ring.rs
- komorebi/src/window_manager.rs
- komorebi/src/workspace.rs
This PR changes the `floating_windows` from a `Vec<Window>` to a `Ring<Window>` which allows us to keep track of the focused floating window. This combined with the existing layer switch allows us to know when we should focus the focused container or the focused floating window.
The 2nd commit of this PR adds the ability to focus the floating windows depending on the direction used. It takes into account the top left corner of each window and uses that to look for the closest top left corner in the direction provided.
If there are no windows found on that direction it then checks if it can focus across monitor.
This commit is a WIP since I want some feedback on the result of the directional focus first.
The 3rd commit of this PR raises and lowers all the floating windows so that they show …
> feat: floating windows improved

- komorebi-client/src/lib.rs
@LGUG2Z We might want to start doing something like `pub use komorebi::core::*`, otherwise things sort of things will always be forgotten until someone needs it. Is there something on `komorebi::core` that shouldn't be exported through the client?
> fix(client): re-export `FloatingLayerBehaviour`

- komorebi-gui/src/main.rs
- komorebi/src/static_config.rs
- komorebi/src/window_manager.rs
Adds the `unfocused_locked` border color to `border_colours` so that users that don't use themes can still customize that color like they do the others.
It also adds that color and the `floating` border color to the `komorebi-gui`.
> fix(wm): add unfocused locked color

- komorebi-bar/src/widgets/komorebi.rs
- komorebi-bar/src/widgets/komorebi_layout.rs
- komorebi-bar/src/widgets/widget.rs
- schema.bar.json
- schema.json
This commit adds a new komorebi widget to indicate whether or not the focused container is locked.
This commit also includes an icon colour change on the layer and layout widgets to the accent colour.
The commit also renames the locked_window widget to locked_container as it is more suitable.
https://github.com/user-attachments/assets/e177aede-1c96-4f3f-a380-4777582e04ce
```json
"locked_container": {
"enable": true,
"display": "Icon",
"show_when_unlocked": true
}
```
> feat(bar): added locked_container widget, use accent colour for icons

- docs/cli/query.md
- komorebi/src/core/mod.rs
- komorebi/src/monitor.rs
- komorebi/src/process_command.rs
- for DefaultLayout: returns enum name.to_string, 
- for CustomLayout: returns "Custom" 
- for floating workspaces: returns "None"
Initially I hoped this could return values in snake case fashion so it would be chainable with `komorebic change-layout`, but I do think that these should not be tied by default, whoever wants to tinker with this (me 😄) should handle it some other way.
This is my first Rust ever so I hope everything is according to the correct practices.
> feat(cli): query focused-workspace-layout

- docs/troubleshooting.md
Updated troubleshooting.md with the workaround for an issue where the Komorebi Bar does not render transparency properly with Nvidia GPUs. I hope this can help other. It was shared with me by @CtByte on #1391. Seems like he was found this on a [discord](url) post
> docs: update troubleshooting.md with Nvidia GPU workaround for bar transparency

- komorebi-bar/src/bar.rs
- komorebi-bar/src/config.rs
- komorebi-bar/src/main.rs
- komorebi-bar/src/render.rs
- komorebi-bar/src/selected_frame.rs
- komorebi-bar/src/widgets/battery.rs
- komorebi-bar/src/widgets/cpu.rs
- komorebi-bar/src/widgets/memory.rs
- komorebi-bar/src/widgets/network.rs
- komorebi-bar/src/widgets/storage.rs
- schema.bar.json
This commit adds new settings to some widgets that allows to auto select/hide them based on their current values.
The cpu/memory/network/storage widgets get a setting that auto selects the widget if the current value/percentage is over a value.
The battery widget gets a setting that auto selects the widget if the current percentage is under a value.
The storage widget gets a setting that auto hides the disk widget if the percentage is under a value.
```json
{
"Memory": {
"enable": true,
"data_refresh_interval": 5,
"label_prefix": "Icon",
"auto_select_over": 40
}
},
{
"Battery": {
"enable": true,
"hide_on_full_charge": true,
"auto_select_under": 15
}
},
{
"Storage": {
"enable": true,
"auto_select_over": 95,
"auto_hide_under": 90
}
},
``` …
> feat(bar): auto select/hide widget based on value

- Cargo.lock
- komorebi-bar/src/widgets/komorebi.rs
- komorebi/Cargo.toml
- komorebi/src/process_command.rs
This commit ensures that the replace-configuration command also replaces bars.
Already running bars are stopped and new bars are started using the new configuration.
> fix(cli): restart bar on replace-configuration

- docs/common-workflows/remove-gaps.md
- komorebi/src/monitor.rs
- komorebi/src/static_config.rs
- komorebi/src/workspace.rs
- schema.json
- Fix wrong docs info, borders are enabled by default but the docs said they were disabled by default.
- Disabling the borders now also ignores the `border_width` and `border_offset`. Previously you would have to set them to 0 after disabling the borders or they would still count for the containers gap. Now if the borders are disabled they are no longer taken into account.
- Setting `"border": false` and then removing that line completely will re-enable the borders as it should since the default is to have them enabled.
> fix: disabled borders remove width + offset

- komorebi/src/core/mod.rs
- komorebi/src/process_event.rs
- komorebi/src/static_config.rs
- komorebi/src/window.rs
- komorebi/src/window_manager.rs
Since it has been asked, here it is! MOAR Configs! 😄 
This commit adds a few more options to combine with the `FloatingLayerBehaviour` which are the multiple situations placement options. Which are the following:
- `"toggle_float_placement"`: the placement to be used by a floating window when it is forced to float with the `toggle-float` command.
- `"floating_layer_placement"`: the placement to be used by a floating window when it is spawned on the floating layer and the user has the floating layer behaviour set to float.
- `"float_override_placement"`: the placement to be used by a window that is spawned when float override is active.
- `"float_rule_placement"`: the placement to be used by a window that matches a 'floating_applications' rule.
Each `Placement` can be one of the following …
> feat(wm): float placement configs

- komorebi/src/animation/style.rs
- komorebi/src/core/animation.rs
This commit adds ability to use cubic-bezier. Cubic-bezier allow to customize smoothness of animation.
Config for cubic-bezier looks like this:
```json
"animation": {
...
"style": [0.32, 0.72, 0, 1],
...
},
```
Previous options for `style` are untouched.
> feat(animation): implements cubic-bezier for animation styles

- komorebi-bar/src/widgets/applications.rs
- komorebi-bar/src/widgets/komorebi.rs
- komorebi-bar/src/widgets/mod.rs
- komorebi-bar/src/widgets/widget.rs
- schema.bar.json
This pull request introduces a new Applications widget that displays a user-defined list of application launchers in the UI. Each app entry supports an icon, a label, and executes its configured command on click.
The design of this widget is inspired by the **Applications Widget** of **YASB Reborn**. I personally missed this functionality and aimed to bring a similar experience to `komorebi-bar`.
- Declarative configuration via ApplicationsConfig and per-app AppConfig.
- Supports display modes: icon-only, text-only, or icon + text.
- Icons can be:
- loaded from image files (.png, .ico, etc.)
- extracted from executable files on Windows (e.g. .exe)
- Optional display of the launch command on hover.
Only image-based icons and Windows .exe embedded icons are currently supported. I made the …
> Add  Applications Widget for Launching Configurable App Shortcuts

- komorebi/src/monitor.rs
- komorebi/src/window_manager.rs
- komorebi/src/workspace.rs
Created tests for testing removing a nonexistent workspace and window, moving a container to a workspace that hasn't been created, moving a workspace to a non existent monitor, and moving a window to a non existent container.
> Edge case tests for monitor, workspace, and window manager

- komorebi/src/border_manager/mod.rs
- komorebi/src/process_command.rs
- komorebi/src/process_event.rs
Allows for having floating windows on the "Floating Layer" over a monocle. When toggling back to the tiling layer it hides the floating windows again.
> feat(wm): floating over monocle

- komorebi-shortcuts/src/main.rs
- Removed command filtering logic from the shortcuts UI.
- All hotkey bindings are now shown regardless of command.
- Improved UI with hint text for the filter input.
> feat(shortcuts): show all hotkey bindings and improve UI

- komorebi/src/monitor.rs
- komorebi/src/process_command.rs
There are currently a number of commands that do not update the previously focused workspace correctly. The previous method relied on handling each case, this change makes it so that last_focused_workspace is always updated whenever the focus is changed.
> fix(wm): move last_focused_workspace logic to focus_workspace method

- komorebi/src/window.rs
- komorebi/src/windows_api.rs
This commit improves move windows animation by adding win32 api calls to force app to rerender window after each frame
> refactor(animations): improve resize behaviour of apps

- komorebi/src/core/mod.rs
- komorebi/src/process_command.rs
- komorebi/src/static_config.rs
- komorebi/src/window_manager.rs
- komorebi/src/workspace.rs
- komorebic.lib.ahk
- komorebic/src/main.rs
This commit adds the option to set 'work_area_offset' per workspace. If no workspace work area offset is set for that workspace it will instead use the value of the globals.work_area_offset for that workspace.
> feat(wm): add the ability to set work-area-offset per workspace

- komorebi/src/lib.rs
- komorebi/src/window_manager.rs
This implements Clone for State, Notification and NotificationEvent to allow for the use of these types in Rhai scripts.
> feat(wm): implement Clone for State, Notification and NotificationEvent
