README.md
=> fix(docs): typo `whkrc` -> `whkdrc`

Cargo.lock, komorebi/Cargo.toml
=> chore(wm): update deps, including miow

komorebi/src/workspace.rs
This fixes the panic, but not the underlying problem.
Updates #757
Updates #758
=> fix(wm): avoid out of range subtraction

komorebi/src/animation.rs, komorebi/src/window.rs, komorebi/src/windows_api.rs
This pull request fixes bug when window get shrunk during the animation posted by @AmN on discord. 
Also pull request renames variables to increase readability.
=> Refactoring and fix window shrunk when animate

komorebic/src/main.rs
Thought it would make sense to add the ahk flag to the stop command, cuz it exists in the start and enable-autostart commands...
I tried to replicate the new command using the others as a base...
Is PowerShell version compatibility something you would like me to ensure? Should I focus on supporting older versions (like PowerShell 5.1 or even earlier), or is it ok to target more modern versions (PowerShell Core 6+)?
Let me know so I can adjust the script...
=> feat: adds the ahk flag to the stop command

komorebi/src/window.rs
This commit adds a `matches_floating_applications` to the `RuleDebug` which allows users to know if a window was matched as a floating window when using the debug part of the GUI.
=> feat(gui): add `matches_floating_applications` to GUI Debugging

komorebi/src/window_manager.rs
=> fix(wm): handle stack commands when stack is monocled

komorebi/src/workspace.rs
This change prevents the move animation to play again for each window in the stack. Tested with all hiding behaviors. Looks good so far.
Maybe I've missed something. Need review
=> fix(animation): sets position for all windows in a container

komorebi-bar/src/network.rs
Refactored the network widget in order to fix the icon color. This ended up greatly simplifying the logic on the widget as well.
```json
"theme": {
"palette": "Catppuccin",
"name": "Latte",
"accent": "Blue"
},
```
before
after
with grouping
=> fix(bar): refactoring network widget

komorebi-client/src/lib.rs
@LGUG2Z This is just a temporary PR in order to create the github actions artifacts so we can tell the user from issue LGUG2Z/whkd#49 to download them and test if it fixes the issue. I don't believe it will, but since it was so simple to try it out I decided to make the PR just so we can discard this option...
=> fix(client): add write-timeout to prevent blocking

komorebi/src/window_manager.rs
This commit makes sure we focus the previously focused workspace on all monitors, load it and update it and in the end focus the actual focused monitor and workspace pair calling `update_focused_workspace` to make sure it updates the workspace and gives focus to the focused window.
=> fix(wm): focus and update after apply state

komorebi-bar/src/bar.rs
For some reason, when calling the `window.set_position` when creating the Komobar or even when applying the config on the first frame the actual EGUI's window size wasn't changing. This commit adds a new field to `Komobar` called `size_rect` so that we can store the expected size rect of the window according to the config, so that we don't have to be calculating it all the time. This field is updated on `apply_config`. Now on `update` of the bar we check if the current size using the EGUI Context is the expected `size_rect`, if it is we do nothing, if it is not we update the bar position again. This makes sure that on start the bar will resize to the users config correctly!
Fixes #1213
=> fix(bar): apply position on start

docs/example-configurations.md
=> docs: fix typo "monocole" -> "monocle"

komorebi/src/window_manager.rs
=> Window manager cycle test and transfer window and container tests

komorebi/src/window_manager.rs
=> fix(wm): keep borders within monitor on move/resize floats

komorebi-bar/src/date.rs, komorebi-bar/src/time.rs
This commit limits the number of times the time and date widgets get a new state.
Even though having a limit of 1 second on the ui repaint, when the bar is focused or hovered, this is ignored and state of these widgets were updated many more times a second.
The time widget looked less accurate and lagging (especially with multiple showing seconds) so the refresh interval is set to be 500 ms instead of 1 second.
=> fix(bar): limit new state freq on time and date

docs/common-workflows/multi-monitor-setup.md
This is my attempt at creating a `Multiple Monitors Setup` section on `Common Workflows`.
Please let me know if you want me to change something.
=> docs(mkdocs): add multi monitor common-workflows section

komorebi/src/window_manager.rs
=> Window manager tests Removing windows and containers and swapping containers

komorebi/src/window_manager.rs
=> Window manager tests monitor tests and tiling state test

komorebi/src/process_command.rs
Fix a bug with the `eager-focus` command
=> fix(wm): correctly focus workspace on eager-focus

komorebi/src/window_manager.rs
This commit adds two tests that test the functions that handle cycling to the next and previous windows.
=> Window manager cycle tests

komorebi/src/workspace.rs
Container tests include testing functions related to removing, adding, and focusing a container and windows.
=> test(workspace.rs): container and Window tests

komorebi/src/container.rs, komorebi/src/monitor.rs, komorebi/src/window_manager.rs
Contains tests for testing various functions in both monitor.rs and containers.rs
=> Monitor and Container tests

komorebi/src/monitor_reconciliator/mod.rs
Added monitor_reconciliator tests to test sending a notification, channel capacity, insert monitor cache for one and two monitors, notification listener, and attached display devices. Also created a Mocking of a monitor that can be used with functions that call the Win32 API.
=> Monitor reconciliator tests notification tests

komorebi/src/workspace.rs
Created tests for testing the functions focus_container_by_window, contains_managed_window, and new_floating_window.
=> Workspace tests

komorebi-bar/src/widgets/komorebi.rs
This commit re-introduces a commit that was lost
original: https://github.com/LGUG2Z/komorebi/commit/36e3eaad36336101321ecafbffdf089795028c1e
blame: https://github.com/LGUG2Z/komorebi/commit/bb31e7155d9eed68b03b54c83e6c4e8fb1e6d84c
fixes: https://github.com/LGUG2Z/komorebi/issues/1388
https://github.com/user-attachments/assets/47f691c7-49a4-4a2f-8b0a-5967c9cb087f
=> fix(bar): re-introduce retain exact workspace indices

komorebi-bar/src/widgets/battery.rs
This commit is changing the icon on the battery widget based on the current level.
100 - 75: discharging 
75 - 50: high
50 - 25: medium
25 - 10: low
10 - 0: warning
=> feat(bar): changing battery icons

komorebi/src/monitor.rs, komorebi/src/workspace.rs
Created tests for testing the ensure_workspace_count, move_container_to_workspace, and visible_windows functions.
=> Workspace and monitor tests

komorebi/src/process_command.rs
When using the eager focus command to focus a window that was hidden on a stack on an unfocused workspace it would load the workspace focus the correct window but keep it cloaked with the previously focused window showing. This would happen because we were focusing the workspace before focusing the window which would create two window focus events, the first one for the previously focused window and the second one for the target window we wanted. The problem was that when the first event was handled it would again refocus that window and cloak the target window again so when the target window focus event came it would ignore it since the `should_manage` function would return `false` because the window was cloaked and had all its window styles as `None`, unless we had transparency enabled, …
=> fix(wm): fix eager focus on hidden stacked window

komorebi/src/window_manager.rs
Created tests for testing the maximize_window, unmaximize_window, monocle_on, monocle_off, toggle_monocle, toggle_maximize, add_window_handle_to_move_based_on_workspace_rule and ensured_named_workspace_for_monitor functions.
=> More tests for Window Manager

komorebi/src/window_manager.rs
Created tests to test switching focus to a nonexistent monitor, swapping a container with a nonexistent container, and swapping a workspace with a nonexistent monitor. PR also contains the bug fix @LGUG2Z fixed, where the container contents were deleted when attempting to swap a container with a nonexistent container. The fix ensures that both containers exist before removing the containers contents.
=> Window Manager Edge Case Tests

komorebi/src/window_manager.rs
Created tests that tests removing nonexistent window, cycling windows in an empty container, and floating a nonexistent window.
=> More window manager edge cases

komorebic/src/main.rs
This commit makes it so the quickstart command first checks for the existence of the config files. If they don't exist it writes them, if they do exist it prompts the user to whether or not they want to overwrite the existing files. Lastly it prints the full path to the files that were written. This is to prevent users from accidentally overwriting their configs as well as making it clearer where komorebi places the config files for new users.
```
PS C:\Users\ollem\rust\komorebi> cargo run --package komorebic quickstart
C:\Users\ollem\komorebi.json will be overwritten, do you want to continue? (y/N): y
C:\Users\ollem\komorebi.bar.json will be overwritten, do you want to continue? (y/N): N
Skipping C:\Users\ollem\komorebi.bar.json
C:\Users\ollem\applications.json will be overwritten, do …
```
=> feat(cli): change quickstart to prompt user before writing files

komorebi-bar/src/widgets/network.rs
This commit ensures that the default interface for the network widget does not update on every render of the bar.
Some people have experienced the bar being frozen and hopefully this will remediate that issue.
=> fix(bar): update network interface less frequently
